#!/usr/bin/with-contenv sh

function setUIDGID() {
  # Setup user/group ids
if [ ! -z "${PLEX_UID}" ]; then
  if [ ! "$(id -u plex)" -eq "${PLEX_UID}" ]; then

    # usermod likes to chown the home directory, so create a new one and use that
    # However, if the new UID is 0, we can't set the home dir back because the
    # UID of 0 is already in use (executing this script).
    if [ ! "${PLEX_UID}" -eq 0 ]; then
      mkdir /tmp/temphome
      usermod -d /tmp/temphome plex
    fi

    # Change the UID
    usermod -o -u "${PLEX_UID}" plex

    # Cleanup the temp home dir
    if [ ! "${PLEX_UID}" -eq 0 ]; then
      usermod -d ${UNICORN_PREFIX} plex
      rm -Rf /tmp/temphome
    fi
  fi
fi

if [ ! -z "${PLEX_GID}" ]; then
  if [ ! "$(id -g plex)" -eq "${PLEX_GID}" ]; then
    groupmod -o -g "${PLEX_GID}" plex
  fi
fi
}

if [ -z "${PLEX_BUILD}" ]; then
  PLEX_BUILD=$(curl -s "${LOADBALANCER_ADDRESS}/?X-Plex-Token=${PLEX_TOKEN}" | xmllint --xpath "string(//MediaContainer/@version)" -)

  if [[ $(expr match "$PLEX_BUILD" '[0-9a-z.]*-[0-9a-z]*') -eq 0 ]]; then
    echo ""
    echo -e "\e[41m"
    echo -e " \e[21m WARNING: Unable to determine ${PLEX_BUILD} from ${LOADBALANCER_ADDRESS} !! "
    echo -e " \e[21m Please check your network connection or Plex Token and try again."
    echo -e "\e[49m"
    echo ""
    exit 1
  fi

  printf "${PLEX_BUILD}" > /var/run/s6/container_environment/PLEX_BUILD

  curl -J -L -o /tmp/plex.deb "https://downloads.plex.tv/plex-media-server-new/${PLEX_BUILD}/debian/plexmediaserver_${PLEX_BUILD}_amd64.deb"
  cd /tmp && ar x /tmp/plex.deb
  tar xf data.tar.xz "./usr/lib/plexmediaserver/Plex Media Server" -C /tmp

  CODECS_BUILD=$(strings "/tmp/usr/lib/plexmediaserver/Plex Media Server" | egrep '^([a-z0-9]){7}-([0-9]){4}$' | grep -v 'windows' | head -1)
  printf "${CODECS_BUILD}" > /var/run/s6/container_environment/CODECS_BUILD

  EAE_VERSION=$(strings "/tmp/usr/lib/plexmediaserver/Plex Media Server" | egrep '^eae-[a-z0-9]+-[0-9]+*$' | head -1)
  printf "${EAE_VERSION}" > /var/run/s6/container_environment/EAE_VERSION

  rm -rf /tmp/*

  echo ""
  echo -e "\e[42m"
  echo -e " \e[21m ----------------------------------------------"
  echo -e " \e[21m Versions:"
  echo -e " \e[21m"
  echo -e " \e[21m PLEX_BUILD=${PLEX_BUILD}"
  echo -e " \e[21m CODECS_BUILD=${CODECS_BUILD}"
  echo -e " \e[21m EAE_VERSION=${EAE_VERSION}"
  echo -e " \e[21m ----------------------------------------------"
  echo -e "\e[49m"
  echo ""
fi

setUIDGID

exit 0
